config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("insta_loader.urls", "insta_loader")),
]

insta_loader/urls.py
from django.urls import path

from insta_loader.views import VideoView, ReelsView, PhotoView, StoryView

app_name = 'insta_loader'
urlpatterns = [
    path("", VideoView.as_view(), name="video"),
    path("story", StoryView.as_view(), name="story"),
    path("photo", PhotoView.as_view(), name="photo"),
    path("reels", ReelsView.as_view(), name="reels"),
]

insta_loader/models.py
from django.db import models

# Create your models here.

insta_loader/views.py
import json
import requests

from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views import View


# Json response data mixin
class JsonResponseDataMixin:
    def get_response_data(self, request):
        api_url = "https://instagram120.p.rapidapi.com/api/instagram/links"
        headers = {
            "Content-Type": "application/json",
            "X-RapidAPI-Key": "14099712b6msha8ec14aa083c8a5p1de149jsn28196a726227",
            "X-RapidAPI-Host": "instagram120.p.rapidapi.com"
        }
        payload = json.dumps(
            {"url": request.POST.get("instagram_url"), }
        )

        response = requests.post(api_url, headers=headers, data=payload)
        return response.json()


class VideoView(View, JsonResponseDataMixin):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            'pages/video.html'
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        data = self.get_response_data(request)
        video_url = None

        if isinstance(data, list):
            for item in data:
                for video in item.get("urls", []):
                    if video.get("extension") == "mp4":
                        video_url = video["url"]
                        break
                if video_url:
                    break

        return render(
            request, "pages/video.html", {
                "video_url": video_url,
                "error": data.get(
                    "message", "Unknown error"
                ) if not video_url else None
            }
        )


class PhotoView(View, JsonResponseDataMixin):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            'pages/photo.html'
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        data = self.get_response_data(request)
        photo_url = data[0]["urls"][0]["url"].replace("&dl=1", "")

        return render(
            request, "pages/photo.html", {
                "photo_url": photo_url,
                "error": data.get(
                    "message", "Unknown error"
                ) if not photo_url else None
            }
        )


class ReelsView(View, JsonResponseDataMixin):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            'pages/reels.html'
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        data = self.get_response_data(request)

        video_url = None
        if isinstance(data, list):
            for item in data:
                for video in item.get("urls", []):
                    if video.get("extension") == "mp4":
                        video_url = video["url"]
                        break
                if video_url:
                    break

        return render(
            request, "pages/reels.html", {
                "video_url": video_url,
                "error": data.get(
                    "message", "Unknown error"
                ) if not video_url else None
            }
        )


class StoryView(View, JsonResponseDataMixin):
    def get(self, request: HttpRequest) -> HttpResponse:
        return render(
            request,
            'pages/story.html'
        )

    def post(self, request: HttpRequest) -> HttpResponse:
        data = self.get_response_data(request)["result"][0]

        video_url = None
        photo_url = None

        if data.get('video_versions'):
            video_url = data['video_versions'][0]["url"]
        else:
            photo_url = data["image_versions2"]['candidates'][1]["url"]

        return render(
            request, "pages/story.html", {
                "video_url": video_url,
                "photo_url": photo_url,
                "error": data.get(
                    "message", "Unknown error"
                )
            }
        )

templates/layout/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  {# Encoding #}
  <meta charset="utf-8">

  {# Title #}
  <title>InstaLoad</title>

  <!-- Bootstrap 5 & Icons CDN -->
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet">
  <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
      rel="stylesheet">

  <!-- static css -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body class="medium-grey">

{# Header #}
<header>
  <nav class="navbar">
    <div class="container p-3">
      <a class="navbar-brand fw-bold gradient-text"
         href="{% url "insta_loader:video" %}">
        <i class="bi bi-instagram"></i>
        InstaLoad
      </a>
      <a href="#footer" class="text-reset text-decoration-none">
        <span class="fw-bold">FAQ</span>
      </a>
    </div>
  </nav>
</header>

<main class="gradient-bg">
  <!-- Content type swithcer -->
  <div class="container text-center p-5">
    <div
        class="text-light d-inline-block rounded rounded-3 p-3 d-flex w-50 justify-content-between m-auto align-items-center">
      <div
          {% if request.path == "/" %}class="p-2 rounded"
          style="background-color: rgba(0,0,0,.5); "{% endif %}>
        <a href="{% url "insta_loader:video" %}"
           class="text-reset text-decoration-none">
          <i class="bi bi-file-play me-2"></i>
          video
        </a>
      </div>

      <div {% if 'photo' in request.path %}class="p-2 rounded"
           style="background-color: rgba(0,0,0,.5); "{% endif %}>
        <a href="{% url "insta_loader:photo" %}"
           class="text-reset text-decoration-none">
          <i class="bi bi-file-image"></i>
          Photo
        </a>
      </div>

      <div {% if 'story' in request.path %}class="p-2 rounded"
           style="background-color: rgba(0,0,0,.5); "{% endif %}>
        <a href="{% url "insta_loader:story" %}"
           class="text-reset text-decoration-none">
          <i class="bi bi-clock-history"></i>
          Story
        </a>
      </div>

      <div {% if 'reels' in request.path %}class="p-2 rounded"
           style="background-color: rgba(0,0,0,.5); "{% endif %}>
        <a href="{% url "insta_loader:reels" %}"
           class="text-reset text-decoration-none">
          <i class="bi bi-camera-reels"></i>
          Reels
        </a>
      </div>
    </div>
  </div>

  <!-- Banner -->
  <div class="container text-center mt-4 text-light">
    <h1 class="p-3">
      Завантаження Instagram Video
    </h1>
    <h4>Скачуй Video та Reels з інстаграму</h4>
  </div>

  <!-- Form -->
  <div class="text-center m-5">
    <form action="" method="POST" class="d-flex justify-content-center gap-2">
      {% csrf_token %}
      <input type="text" name="instagram_url" class="w-25 form-control"
             placeholder="Insert link here">
      <button class="btn btn-secondary">Paste</button>
      <input type="submit" value="Download" class="btn btn-primary">
    </form>
  </div>

  <!-- Content  -->
  {% block content %}{% endblock %}

  <!-- Story  Video  Reels  -->
  <div class="container">
    <div class="mx-auto" style="max-width:800px;">
      <div class="row row-cols-1 row-cols-md-2 g-3">

        <!-- Photo Downloader -->
        <div class="col">
          <div
              class="d-flex align-items-start bg-light text-muted rounded p-3 h-100">
            <i class="bi bi-file-image pe-3 fs-3 gradient-text"></i>
            <div>
              <h6 class="fw-semibold mb-1">Photo Downloader</h6>
              <small>Якщо ви шукаєте спосіб зберігати зображення з публікацій в
                Instagram, InstaLoad дозволяє завантажувати окремі зображення
                або повні каруселі.</small>
            </div>
          </div>
        </div>

        <!-- Story Downloader -->
        <div class="col">
          <div
              class="d-flex align-items-start bg-light text-muted rounded p-3 h-100">
            <i class="bi bi-clock-history pe-3 fs-3 gradient-text"></i>
            <div>
              <h6 class="fw-semibold mb-1">Story Downloader</h6>
              <small>Зберігайте, переглядайте та використовуйте історії
                повторно навіть через 24 години — додаток не потрібен!</small>
            </div>
          </div>
        </div>

        <!-- Video Downloader -->
        <div class="col">
          <div
              class="d-flex align-items-start bg-light text-muted rounded p-3 h-100">
            <i class="bi bi-file-play pe-3 fs-3 gradient-text"></i>
            <div>
              <h6 class="fw-semibold mb-1">Video Downloader</h6>
              <small>Завантажуйте одне або кілька відео з каруселей Instagram
                за лічені секунди.</small>
            </div>
          </div>
        </div>

        <!-- Reels Downloader -->
        <div class="col">
          <div
              class="d-flex align-items-start bg-light text-muted rounded p-3 h-100">
            <i class="bi bi-camera-reels pe-3 fs-3 gradient-text"></i>
            <div>
              <h6 class="fw-semibold mb-1">Reels Downloader</h6>
              <small>Хапайте свої улюблені ролики та дивіться їх будь-коли за
                допомогою InstaLoad.</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- HOW-TO STEPS -->
  <div class="container mt-5 text-light p-5">
    <h2 class="text-center mb-5 fw-bold">How to download reels
      from Instagram?
    </h2>

    <!-- Step 1 -->
    <div class="d-flex mb-5 ms-5">
      <div>
        <div class="d-flex align-items-center mb-2">
          <span class="badge bg-danger rounded-circle me-3"
                style="width:30px; height:30px;">1</span>
          <h5 class="mb-0 fw-semibold">Copy the URL</h5>
        </div>
        <p>
          First, open the Instagram Reels video you wish to download. Tap the
          <strong>•••</strong> icon and choose <em>Copy Link</em>.
        </p>
      </div>
    </div>

    <!-- Step 2 -->
    <div class="d-flex mb-5 ms-5">
      <div>
        <div class="d-flex align-items-center mb-2">
          <span class="badge bg-danger rounded-circle me-3"
                style="width:30px; height:30px;">2</span>
          <h5 class="mb-0 fw-semibold">Paste the link</h5>
        </div>
        <p>
          Go to <strong>InstaLoad</strong>, paste the link into the field, then
          click the <em>Download</em> button.
        </p>
      </div>
    </div>

    <!-- Step 3 -->
    <div class="d-flex ms-5">
      <div>
        <div class="d-flex align-items-center mb-2">
          <span class="badge bg-danger rounded-circle me-3"
                style="width:30px; height:30px;">3</span>
          <h5 class="mb-0 fw-semibold">Download</h5>
        </div>
        <p>
          Choose the quality and format you prefer and save the Reels video to
          your device.
        </p>
      </div>
    </div>
  </div>

  <!-- Styles  -->
  <style>
      .step-dot-left {
          width: 12px;
          height: 12px;
          border-radius: 50%;
          background: #ffffff; /* white */
          margin-top: 0.35rem; /* aligns with text */
      }
  </style>
</main>

{# Footer #}
<footer id="footer" class="dark-grey p-4">
  <div class="container d-flex justify-content-center align-items-center">
    &copy; 2025 Viktor Umanskiy
  </div>
</footer>

{# Botstrap js #}
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js">
</script>
</body>
</html>

templates/pages/photo.html
{% extends "layout/base.html" %}

{% block content %}
  <div class="container my-5 m-auto">
    {% if photo_url %}
      <div class=" m-auto text-center">
        <img src="{{ photo_url }}" alt="Not allowed photo"/>
      </div>
    {% endif %}

    {% if error %}
      <div class="alert alert-danger text-center" role="alert">
        {{ error }}
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/pages/reels.html
{% extends "layout/base.html" %}

{% block content %}

  <div class="container my-5">
    {% if video_url %}
      <div class="ratio ratio-16x9 rounded shadow-sm overflow-hidden">
        <video class="w-100 h-100" controls>
          <source src="{{ video_url }}" type="video/mp4">
          Ваш браузер не підтримує тег <code>&lt;video&gt;</code>.
        </video>
      </div>

    {% elif error %}
      <div class="alert alert-danger text-center" role="alert">
        {{ error }}
      </div>
    {% endif %}
  </div>

{% endblock %}

templates/pages/story.html
{% extends "layout/base.html" %}

{% block content %}

  {% if video_url %}
    <div class="container my-5">
      <div class="ratio ratio-16x9 rounded shadow-sm overflow-hidden">
        <video class="w-100 h-100" controls>
          <source src="{{ video_url }}" type="video/mp4">
          Ваш браузер не підтримує тег <code>&lt;video&gt;</code>.
        </video>
      </div>
    </div>

  {% elif photo_url %}
    <div class="container mt-5 text-center">
      <div class="alert alert-danger text-center" role="alert">
        Only video stories allowed !!!
      </div>
    </div>

  {% elif error %}
    <div class="alert alert-danger text-center" role="alert">
      {{ error }}
    </div>
  {% endif %}

{% endblock %}

templates/pages/video.html
{% extends "layout/base.html" %}

{% block content %}

  <div class="container my-5">
    {% if video_url %}
      <div class="ratio ratio-16x9 rounded shadow-sm overflow-hidden">
        <video class="w-100 h-100" controls>
          <source src="{{ video_url }}" type="video/mp4">
          Ваш браузер не підтримує тег <code>&lt;video&gt;</code>.
        </video>
      </div>

    {% elif error %}
      <div class="alert alert-danger text-center" role="alert">
        {{ error }}
      </div>
    {% endif %}
  </div>

{% endblock %}